server:
  port: 8088
spring:
  application:
    name: search-service
  data:
    elasticsearch:
      cluster-nodes: 192.168.58.132:9300
  main:
    allow-bean-definition-overriding: true
  rabbitmq:
    host: 192.168.58.132
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10087/eureka
    registry-fetch-interval-seconds: 5
  instance:
      lease-renewal-interval-in-seconds: 5
      lease-expiration-duration-in-seconds: 10

