server:
  port: 8085
spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://localhost:3306/leyou?serverTimezone=UTC
    username: root
    password: zhu9884
    hikari:
      maximum-pool-size: 30
      minimum-idle: 10
  rabbitmq:
    host: 192.168.58.132
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10087/eureka
  instance:
    lease-renewal-interval-in-seconds: 5 # 每隔5秒发送一次心跳
    lease-expiration-duration-in-seconds: 10 # 10秒不发送就过期
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}:${server.port}

mybatis:
  type-aliases-package: com.leyou.dao
  mapper-locations: classpath:mappers/*.xml
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    com.leyou.dao.*: debug   #打印sql